import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home({ plants }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Platns blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Plants Blog
        </h1>
        <ul>
          {plants.map(plant => (
            <li key={plant.slug}>
              <Link href={`/${plant.slug}`}>
                <a>{plant.plantName}</a>
              </Link>
            </li>
          ))}
        </ul>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const url = `https://graphql.contentful.com/content/v1/spaces/${process.env.CONTENTFUL_SPACE_ID}/environments/master`
  const query = `
    query GetAllPlants {
      plantCollection{
        items{
          plantName
          slug
        }
      }
    }
  `
  const result = await fetch(url, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${process.env.CONTENTFUL_DELIVERY_TOKEN}`,
      'Content-type': 'application/json'
    },
    body: JSON.stringify({ query })
  })

  if (!result.ok) {
    console.log(result)
    return {}
  }

  const { data } = await result.json()
  const plants = data.plantCollection.items

  return {
    props: { plants }
  }
}